<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\General\Comuna;

class ComunaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Comuna::insert([
          ['id' => '1101','nombre' => 'Iquique','region_id' => '1'],
          ['id' => '1102','nombre' => 'Camiña','region_id' => '1'],
          ['id' => '1103','nombre' => 'Colchane','region_id' => '1'],
          ['id' => '1107','nombre' => 'Alto Hospicio','region_id' => '1'],
          ['id' => '1401','nombre' => 'Pozo Almonte','region_id' => '1'],
          ['id' => '1404','nombre' => 'Huara','region_id' => '1'],
          ['id' => '1405','nombre' => 'Pica','region_id' => '1'],
          ['id' => '2101','nombre' => 'Antofagasta','region_id' => '2'],
          ['id' => '2102','nombre' => 'Mejillones','region_id' => '2'],
          ['id' => '2103','nombre' => 'Sierra Gorda','region_id' => '2'],
          ['id' => '2104','nombre' => 'Taltal','region_id' => '2'],
          ['id' => '2201','nombre' => 'Calama','region_id' => '2'],
          ['id' => '2202','nombre' => 'Ollagüe','region_id' => '2'],
          ['id' => '2203','nombre' => 'San Pedro de Atacama','region_id' => '2'],
          ['id' => '2301','nombre' => 'Tocopilla','region_id' => '2'],
          ['id' => '2302','nombre' => 'María Elena','region_id' => '2'],
          ['id' => '3101','nombre' => 'Copiapó','region_id' => '3'],
          ['id' => '3102','nombre' => 'Caldera','region_id' => '3'],
          ['id' => '3103','nombre' => 'Tierra Amarilla','region_id' => '3'],
          ['id' => '3201','nombre' => 'Chañaral','region_id' => '3'],
          ['id' => '3202','nombre' => 'Diego de Almagro','region_id' => '3'],
          ['id' => '3301','nombre' => 'Vallenar','region_id' => '3'],
          ['id' => '3302','nombre' => 'Alto del Carmen','region_id' => '3'],
          ['id' => '3303','nombre' => 'Freirina','region_id' => '3'],
          ['id' => '3304','nombre' => 'Huasco','region_id' => '3'],
          ['id' => '4101','nombre' => 'La Serena','region_id' => '4'],
          ['id' => '4102','nombre' => 'Coquimbo','region_id' => '4'],
          ['id' => '4103','nombre' => 'Andacollo','region_id' => '4'],
          ['id' => '4104','nombre' => 'La Higuera','region_id' => '4'],
          ['id' => '4105','nombre' => 'Paiguano','region_id' => '4'],
          ['id' => '4106','nombre' => 'Vicuña','region_id' => '4'],
          ['id' => '4201','nombre' => 'Illapel','region_id' => '4'],
          ['id' => '4202','nombre' => 'Canela','region_id' => '4'],
          ['id' => '4203','nombre' => 'Los Vilos','region_id' => '4'],
          ['id' => '4204','nombre' => 'Salamanca','region_id' => '4'],
          ['id' => '4301','nombre' => 'Ovalle','region_id' => '4'],
          ['id' => '4302','nombre' => 'Combarbalá','region_id' => '4'],
          ['id' => '4303','nombre' => 'Monte Patria','region_id' => '4'],
          ['id' => '4304','nombre' => 'Punitaqui','region_id' => '4'],
          ['id' => '4305','nombre' => 'Río Hurtado','region_id' => '4'],
          ['id' => '5101','nombre' => 'Valparaíso','region_id' => '5'],
          ['id' => '5102','nombre' => 'Casablanca','region_id' => '5'],
          ['id' => '5103','nombre' => 'Concón','region_id' => '5'],
          ['id' => '5104','nombre' => 'Juan Fernández','region_id' => '5'],
          ['id' => '5105','nombre' => 'Puchuncaví','region_id' => '5'],
          ['id' => '5106','nombre' => 'Quilpué','region_id' => '5'],
          ['id' => '5107','nombre' => 'Quintero','region_id' => '5'],
          ['id' => '5108','nombre' => 'Villa Alemana','region_id' => '5'],
          ['id' => '5109','nombre' => 'Viña del Mar','region_id' => '5'],
          ['id' => '5201','nombre' => 'Isla de Pascua','region_id' => '5'],
          ['id' => '5301','nombre' => 'Los Andes','region_id' => '5'],
          ['id' => '5302','nombre' => 'Calle Larga','region_id' => '5'],
          ['id' => '5303','nombre' => 'Rinconada','region_id' => '5'],
          ['id' => '5304','nombre' => 'San Esteban','region_id' => '5'],
          ['id' => '5401','nombre' => 'La Ligua','region_id' => '5'],
          ['id' => '5402','nombre' => 'Cabildo','region_id' => '5'],
          ['id' => '5403','nombre' => 'Papudo','region_id' => '5'],
          ['id' => '5404','nombre' => 'Petorca','region_id' => '5'],
          ['id' => '5405','nombre' => 'Zapallar','region_id' => '5'],
          ['id' => '5501','nombre' => 'Quillota','region_id' => '5'],
          ['id' => '5502','nombre' => 'Calera','region_id' => '5'],
          ['id' => '5503','nombre' => 'Hijuelas','region_id' => '5'],
          ['id' => '5504','nombre' => 'La Cruz','region_id' => '5'],
          ['id' => '5505','nombre' => 'Limache','region_id' => '5'],
          ['id' => '5506','nombre' => 'Nogales','region_id' => '5'],
          ['id' => '5507','nombre' => 'Olmué','region_id' => '5'],
          ['id' => '5601','nombre' => 'San Antonio','region_id' => '5'],
          ['id' => '5602','nombre' => 'Algarrobo','region_id' => '5'],
          ['id' => '5603','nombre' => 'Cartagena','region_id' => '5'],
          ['id' => '5604','nombre' => 'El Quisco','region_id' => '5'],
          ['id' => '5605','nombre' => 'El Tabo','region_id' => '5'],
          ['id' => '5606','nombre' => 'Santo Domingo','region_id' => '5'],
          ['id' => '5701','nombre' => 'San Felipe','region_id' => '5'],
          ['id' => '5702','nombre' => 'Catemu','region_id' => '5'],
          ['id' => '5703','nombre' => 'Llaillay','region_id' => '5'],
          ['id' => '5704','nombre' => 'Panquehue','region_id' => '5'],
          ['id' => '5705','nombre' => 'Putaendo','region_id' => '5'],
          ['id' => '5706','nombre' => 'Santa María','region_id' => '5'],
          ['id' => '6101','nombre' => 'Rancagua','region_id' => '6'],
          ['id' => '6102','nombre' => 'Codegua','region_id' => '6'],
          ['id' => '6103','nombre' => 'Coinco','region_id' => '6'],
          ['id' => '6104','nombre' => 'Coltauco','region_id' => '6'],
          ['id' => '6105','nombre' => 'Doñihue','region_id' => '6'],
          ['id' => '6106','nombre' => 'Graneros','region_id' => '6'],
          ['id' => '6107','nombre' => 'Las Cabras','region_id' => '6'],
          ['id' => '6108','nombre' => 'Machalí','region_id' => '6'],
          ['id' => '6109','nombre' => 'Malloa','region_id' => '6'],
          ['id' => '6110','nombre' => 'Mostazal','region_id' => '6'],
          ['id' => '6111','nombre' => 'Olivar','region_id' => '6'],
          ['id' => '6112','nombre' => 'Peumo','region_id' => '6'],
          ['id' => '6113','nombre' => 'Pichidegua','region_id' => '6'],
          ['id' => '6114','nombre' => 'Quinta de Tilcoco','region_id' => '6'],
          ['id' => '6115','nombre' => 'Rengo','region_id' => '6'],
          ['id' => '6116','nombre' => 'Requínoa','region_id' => '6'],
          ['id' => '6117','nombre' => 'San Vicente','region_id' => '6'],
          ['id' => '6201','nombre' => 'Pichilemu','region_id' => '6'],
          ['id' => '6202','nombre' => 'La Estrella','region_id' => '6'],
          ['id' => '6203','nombre' => 'Litueche','region_id' => '6'],
          ['id' => '6204','nombre' => 'Marchihue','region_id' => '6'],
          ['id' => '6205','nombre' => 'Navidad','region_id' => '6'],
          ['id' => '6206','nombre' => 'Paredones','region_id' => '6'],
          ['id' => '6301','nombre' => 'San Fernando','region_id' => '6'],
          ['id' => '6302','nombre' => 'Chépica','region_id' => '6'],
          ['id' => '6303','nombre' => 'Chimbarongo','region_id' => '6'],
          ['id' => '6304','nombre' => 'Lolol','region_id' => '6'],
          ['id' => '6305','nombre' => 'Nancagua','region_id' => '6'],
          ['id' => '6306','nombre' => 'Palmilla','region_id' => '6'],
          ['id' => '6307','nombre' => 'Peralillo','region_id' => '6'],
          ['id' => '6308','nombre' => 'Placilla','region_id' => '6'],
          ['id' => '6309','nombre' => 'Pumanque','region_id' => '6'],
          ['id' => '6310','nombre' => 'Santa Cruz','region_id' => '6'],
          ['id' => '7101','nombre' => 'Talca','region_id' => '7'],
          ['id' => '7102','nombre' => 'Constitución','region_id' => '7'],
          ['id' => '7103','nombre' => 'Curepto','region_id' => '7'],
          ['id' => '7104','nombre' => 'Empedrado','region_id' => '7'],
          ['id' => '7105','nombre' => 'Maule','region_id' => '7'],
          ['id' => '7106','nombre' => 'Pelarco','region_id' => '7'],
          ['id' => '7107','nombre' => 'Pencahue','region_id' => '7'],
          ['id' => '7108','nombre' => 'Río Claro','region_id' => '7'],
          ['id' => '7109','nombre' => 'San Clemente','region_id' => '7'],
          ['id' => '7110','nombre' => 'San Rafael','region_id' => '7'],
          ['id' => '7201','nombre' => 'Cauquenes','region_id' => '7'],
          ['id' => '7202','nombre' => 'Chanco','region_id' => '7'],
          ['id' => '7203','nombre' => 'Pelluhue','region_id' => '7'],
          ['id' => '7301','nombre' => 'Curicó','region_id' => '7'],
          ['id' => '7302','nombre' => 'Hualañé','region_id' => '7'],
          ['id' => '7303','nombre' => 'Licantén','region_id' => '7'],
          ['id' => '7304','nombre' => 'Molina','region_id' => '7'],
          ['id' => '7305','nombre' => 'Rauco','region_id' => '7'],
          ['id' => '7306','nombre' => 'Romeral','region_id' => '7'],
          ['id' => '7307','nombre' => 'Sagrada Familia','region_id' => '7'],
          ['id' => '7308','nombre' => 'Teno','region_id' => '7'],
          ['id' => '7309','nombre' => 'Vichuquén','region_id' => '7'],
          ['id' => '7401','nombre' => 'Linares','region_id' => '7'],
          ['id' => '7402','nombre' => 'Colbún','region_id' => '7'],
          ['id' => '7403','nombre' => 'Longaví','region_id' => '7'],
          ['id' => '7404','nombre' => 'Parral','region_id' => '7'],
          ['id' => '7405','nombre' => 'Retiro','region_id' => '7'],
          ['id' => '7406','nombre' => 'San Javier','region_id' => '7'],
          ['id' => '7407','nombre' => 'Villa Alegre','region_id' => '7'],
          ['id' => '7408','nombre' => 'Yerbas Buenas','region_id' => '7'],
          ['id' => '8101','nombre' => 'Concepción','region_id' => '8'],
          ['id' => '8102','nombre' => 'Coronel','region_id' => '8'],
          ['id' => '8103','nombre' => 'Chiguayante','region_id' => '8'],
          ['id' => '8104','nombre' => 'Florida','region_id' => '8'],
          ['id' => '8105','nombre' => 'Hualqui','region_id' => '8'],
          ['id' => '8106','nombre' => 'Lota','region_id' => '8'],
          ['id' => '8107','nombre' => 'Penco','region_id' => '8'],
          ['id' => '8108','nombre' => 'San Pedro de la paz','region_id' => '8'],
          ['id' => '8109','nombre' => 'Santa Juana','region_id' => '8'],
          ['id' => '8110','nombre' => 'Talcahuano','region_id' => '8'],
          ['id' => '8111','nombre' => 'Tomé','region_id' => '8'],
          ['id' => '8112','nombre' => 'Hualpén','region_id' => '8'],
          ['id' => '8201','nombre' => 'Lebu','region_id' => '8'],
          ['id' => '8202','nombre' => 'Arauco','region_id' => '8'],
          ['id' => '8203','nombre' => 'Cañete','region_id' => '8'],
          ['id' => '8204','nombre' => 'Contulmo','region_id' => '8'],
          ['id' => '8205','nombre' => 'Curanilahue','region_id' => '8'],
          ['id' => '8206','nombre' => 'Los Alamos','region_id' => '8'],
          ['id' => '8207','nombre' => 'Tirúa','region_id' => '8'],
          ['id' => '8301','nombre' => 'Los Ángeles','region_id' => '8'],
          ['id' => '8302','nombre' => 'Antuco','region_id' => '8'],
          ['id' => '8303','nombre' => 'Cabrero','region_id' => '8'],
          ['id' => '8304','nombre' => 'Laja','region_id' => '8'],
          ['id' => '8305','nombre' => 'Mulchén','region_id' => '8'],
          ['id' => '8306','nombre' => 'Nacimiento','region_id' => '8'],
          ['id' => '8307','nombre' => 'Negrete','region_id' => '8'],
          ['id' => '8308','nombre' => 'Quilaco','region_id' => '8'],
          ['id' => '8309','nombre' => 'Quilleco','region_id' => '8'],
          ['id' => '8310','nombre' => 'San Rosendo','region_id' => '8'],
          ['id' => '8311','nombre' => 'Santa Bárbara','region_id' => '8'],
          ['id' => '8312','nombre' => 'Tucapel','region_id' => '8'],
          ['id' => '8313','nombre' => 'Yumbel','region_id' => '8'],
          ['id' => '8314','nombre' => 'Alto Biobío','region_id' => '8'],
          ['id' => '8401','nombre' => 'Chillán','region_id' => '8'],
          ['id' => '8402','nombre' => 'Bulnes','region_id' => '8'],
          ['id' => '8403','nombre' => 'Cobquecura','region_id' => '8'],
          ['id' => '8404','nombre' => 'Coelemu','region_id' => '8'],
          ['id' => '8405','nombre' => 'Coihueco','region_id' => '8'],
          ['id' => '8406','nombre' => 'Chillán Viejo','region_id' => '8'],
          ['id' => '8407','nombre' => 'El Carmen','region_id' => '8'],
          ['id' => '8408','nombre' => 'Ninhue','region_id' => '8'],
          ['id' => '8409','nombre' => 'Ñiquén','region_id' => '8'],
          ['id' => '8410','nombre' => 'Pemuco','region_id' => '8'],
          ['id' => '8411','nombre' => 'Pinto','region_id' => '8'],
          ['id' => '8412','nombre' => 'Portezuelo','region_id' => '8'],
          ['id' => '8413','nombre' => 'Quillón','region_id' => '8'],
          ['id' => '8414','nombre' => 'Quirihue','region_id' => '8'],
          ['id' => '8415','nombre' => 'Ránquil','region_id' => '8'],
          ['id' => '8416','nombre' => 'San Carlos','region_id' => '8'],
          ['id' => '8417','nombre' => 'San Fabián','region_id' => '8'],
          ['id' => '8418','nombre' => 'San Ignacio','region_id' => '8'],
          ['id' => '8419','nombre' => 'San Nicolás','region_id' => '8'],
          ['id' => '8420','nombre' => 'Treguaco','region_id' => '8'],
          ['id' => '8421','nombre' => 'Yungay','region_id' => '8'],
          ['id' => '9101','nombre' => 'Temuco','region_id' => '9'],
          ['id' => '9102','nombre' => 'Carahue','region_id' => '9'],
          ['id' => '9103','nombre' => 'Cunco','region_id' => '9'],
          ['id' => '9104','nombre' => 'Curarrehue','region_id' => '9'],
          ['id' => '9105','nombre' => 'Freire','region_id' => '9'],
          ['id' => '9106','nombre' => 'Galvarino','region_id' => '9'],
          ['id' => '9107','nombre' => 'Gorbea','region_id' => '9'],
          ['id' => '9108','nombre' => 'Lautaro','region_id' => '9'],
          ['id' => '9109','nombre' => 'Loncoche','region_id' => '9'],
          ['id' => '9110','nombre' => 'Melipeuco','region_id' => '9'],
          ['id' => '9111','nombre' => 'Nueva imperial','region_id' => '9'],
          ['id' => '9112','nombre' => 'Padre las casas','region_id' => '9'],
          ['id' => '9113','nombre' => 'Perquenco','region_id' => '9'],
          ['id' => '9114','nombre' => 'Pitrufquén','region_id' => '9'],
          ['id' => '9115','nombre' => 'Pucón','region_id' => '9'],
          ['id' => '9116','nombre' => 'Saavedra','region_id' => '9'],
          ['id' => '9117','nombre' => 'Teodoro Schmidt','region_id' => '9'],
          ['id' => '9118','nombre' => 'Toltén','region_id' => '9'],
          ['id' => '9119','nombre' => 'Vilcún','region_id' => '9'],
          ['id' => '9120','nombre' => 'Villarrica','region_id' => '9'],
          ['id' => '9121','nombre' => 'Cholchol','region_id' => '9'],
          ['id' => '9201','nombre' => 'Angol','region_id' => '9'],
          ['id' => '9202','nombre' => 'Collipulli','region_id' => '9'],
          ['id' => '9203','nombre' => 'Curacautín','region_id' => '9'],
          ['id' => '9204','nombre' => 'Ercilla','region_id' => '9'],
          ['id' => '9205','nombre' => 'Lonquimay','region_id' => '9'],
          ['id' => '9206','nombre' => 'Los sauces','region_id' => '9'],
          ['id' => '9207','nombre' => 'Lumaco','region_id' => '9'],
          ['id' => '9208','nombre' => 'Purén','region_id' => '9'],
          ['id' => '9209','nombre' => 'Renaico','region_id' => '9'],
          ['id' => '9210','nombre' => 'Traiguén','region_id' => '9'],
          ['id' => '9211','nombre' => 'Victoria','region_id' => '9'],
          ['id' => '10101','nombre' => 'Puerto Montt','region_id' => '10'],
          ['id' => '10102','nombre' => 'Calbuco','region_id' => '10'],
          ['id' => '10103','nombre' => 'Cochamó','region_id' => '10'],
          ['id' => '10104','nombre' => 'Fresia','region_id' => '10'],
          ['id' => '10105','nombre' => 'Frutillar','region_id' => '10'],
          ['id' => '10106','nombre' => 'Los Muermos','region_id' => '10'],
          ['id' => '10107','nombre' => 'Llanquihue','region_id' => '10'],
          ['id' => '10108','nombre' => 'Maullín','region_id' => '10'],
          ['id' => '10109','nombre' => 'Puerto varas','region_id' => '10'],
          ['id' => '10201','nombre' => 'Castro','region_id' => '10'],
          ['id' => '10202','nombre' => 'Ancud','region_id' => '10'],
          ['id' => '10203','nombre' => 'Chonchi','region_id' => '10'],
          ['id' => '10204','nombre' => 'Curaco de vélez','region_id' => '10'],
          ['id' => '10205','nombre' => 'Dalcahue','region_id' => '10'],
          ['id' => '10206','nombre' => 'Puqueldón','region_id' => '10'],
          ['id' => '10207','nombre' => 'Queilén','region_id' => '10'],
          ['id' => '10208','nombre' => 'Quellón','region_id' => '10'],
          ['id' => '10209','nombre' => 'Quemchi','region_id' => '10'],
          ['id' => '10210','nombre' => 'Quinchao','region_id' => '10'],
          ['id' => '10301','nombre' => 'Osorno','region_id' => '10'],
          ['id' => '10302','nombre' => 'Puerto Octay','region_id' => '10'],
          ['id' => '10303','nombre' => 'Purranque','region_id' => '10'],
          ['id' => '10304','nombre' => 'Puyehue','region_id' => '10'],
          ['id' => '10305','nombre' => 'Río Negro','region_id' => '10'],
          ['id' => '10306','nombre' => 'San Juan de la costa','region_id' => '10'],
          ['id' => '10307','nombre' => 'San Pablo','region_id' => '10'],
          ['id' => '10401','nombre' => 'Chaitén','region_id' => '10'],
          ['id' => '10402','nombre' => 'Futaleufú','region_id' => '10'],
          ['id' => '10403','nombre' => 'Hualaihué','region_id' => '10'],
          ['id' => '10404','nombre' => 'Palena','region_id' => '10'],
          ['id' => '11101','nombre' => 'Coihaique','region_id' => '11'],
          ['id' => '11102','nombre' => 'Lago Verde','region_id' => '11'],
          ['id' => '11201','nombre' => 'Aisén','region_id' => '11'],
          ['id' => '11202','nombre' => 'Cisnes','region_id' => '11'],
          ['id' => '11203','nombre' => 'Guaitecas','region_id' => '11'],
          ['id' => '11301','nombre' => 'Cochrane','region_id' => '11'],
          ['id' => '11302','nombre' => 'O´higgins','region_id' => '11'],
          ['id' => '11303','nombre' => 'Tortel','region_id' => '11'],
          ['id' => '11401','nombre' => 'Chile Chico','region_id' => '11'],
          ['id' => '11402','nombre' => 'Río Ibáñez','region_id' => '11'],
          ['id' => '12101','nombre' => 'Punta Arenas','region_id' => '12'],
          ['id' => '12102','nombre' => 'Laguna Blanca','region_id' => '12'],
          ['id' => '12103','nombre' => 'Río Verde','region_id' => '12'],
          ['id' => '12104','nombre' => 'San Gregorio','region_id' => '12'],
          ['id' => '12201','nombre' => 'Cabo de Hornos','region_id' => '12'],
          ['id' => '12202','nombre' => 'Antártica','region_id' => '12'],
          ['id' => '12301','nombre' => 'Porvenir','region_id' => '12'],
          ['id' => '12302','nombre' => 'Primavera','region_id' => '12'],
          ['id' => '12303','nombre' => 'Timaukel','region_id' => '12'],
          ['id' => '12401','nombre' => 'Natales','region_id' => '12'],
          ['id' => '12402','nombre' => 'Torres del Paine','region_id' => '12'],
          ['id' => '13101','nombre' => 'Santiago','region_id' => '13'],
          ['id' => '13102','nombre' => 'Cerrillos','region_id' => '13'],
          ['id' => '13103','nombre' => 'Cerro Navia','region_id' => '13'],
          ['id' => '13104','nombre' => 'Conchalí','region_id' => '13'],
          ['id' => '13105','nombre' => 'El Bosque','region_id' => '13'],
          ['id' => '13106','nombre' => 'Estación Central','region_id' => '13'],
          ['id' => '13107','nombre' => 'Huechuraba','region_id' => '13'],
          ['id' => '13108','nombre' => 'Independencia','region_id' => '13'],
          ['id' => '13109','nombre' => 'La Cisterna','region_id' => '13'],
          ['id' => '13110','nombre' => 'La Florida','region_id' => '13'],
          ['id' => '13111','nombre' => 'La Granja','region_id' => '13'],
          ['id' => '13112','nombre' => 'La Pintana','region_id' => '13'],
          ['id' => '13113','nombre' => 'La Reina','region_id' => '13'],
          ['id' => '13114','nombre' => 'Las Condes','region_id' => '13'],
          ['id' => '13115','nombre' => 'Lo Barnechea','region_id' => '13'],
          ['id' => '13116','nombre' => 'Lo Espejo','region_id' => '13'],
          ['id' => '13117','nombre' => 'Lo Prado','region_id' => '13'],
          ['id' => '13118','nombre' => 'Macul','region_id' => '13'],
          ['id' => '13119','nombre' => 'Maipú','region_id' => '13'],
          ['id' => '13120','nombre' => 'Ñuñoa','region_id' => '13'],
          ['id' => '13121','nombre' => 'Pedro Aguirre Cerda','region_id' => '13'],
          ['id' => '13122','nombre' => 'Peñalolén','region_id' => '13'],
          ['id' => '13123','nombre' => 'Providencia','region_id' => '13'],
          ['id' => '13124','nombre' => 'Pudahuel','region_id' => '13'],
          ['id' => '13125','nombre' => 'Quilicura','region_id' => '13'],
          ['id' => '13126','nombre' => 'Quinta Normal','region_id' => '13'],
          ['id' => '13127','nombre' => 'Recoleta','region_id' => '13'],
          ['id' => '13128','nombre' => 'Renca','region_id' => '13'],
          ['id' => '13129','nombre' => 'San Joaquín','region_id' => '13'],
          ['id' => '13130','nombre' => 'San miguel','region_id' => '13'],
          ['id' => '13131','nombre' => 'San ramón','region_id' => '13'],
          ['id' => '13132','nombre' => 'Vitacura','region_id' => '13'],
          ['id' => '13201','nombre' => 'Puente Alto','region_id' => '13'],
          ['id' => '13202','nombre' => 'Pirque','region_id' => '13'],
          ['id' => '13203','nombre' => 'San José de maipo','region_id' => '13'],
          ['id' => '13301','nombre' => 'Colina','region_id' => '13'],
          ['id' => '13302','nombre' => 'Lampa','region_id' => '13'],
          ['id' => '13303','nombre' => 'Tiltil','region_id' => '13'],
          ['id' => '13401','nombre' => 'San Bernardo','region_id' => '13'],
          ['id' => '13402','nombre' => 'Buin','region_id' => '13'],
          ['id' => '13403','nombre' => 'Calera de Tango','region_id' => '13'],
          ['id' => '13404','nombre' => 'Paine','region_id' => '13'],
          ['id' => '13501','nombre' => 'Melipilla','region_id' => '13'],
          ['id' => '13502','nombre' => 'Alhué','region_id' => '13'],
          ['id' => '13503','nombre' => 'Curacaví','region_id' => '13'],
          ['id' => '13504','nombre' => 'María Pinto','region_id' => '13'],
          ['id' => '13505','nombre' => 'San Pedro','region_id' => '13'],
          ['id' => '13601','nombre' => 'Talagante','region_id' => '13'],
          ['id' => '13602','nombre' => 'El Monte','region_id' => '13'],
          ['id' => '13603','nombre' => 'Isla de Maipo','region_id' => '13'],
          ['id' => '13604','nombre' => 'Padre Hurtado','region_id' => '13'],
          ['id' => '13605','nombre' => 'Peñaflor','region_id' => '13'],
          ['id' => '14101','nombre' => 'Valdivia','region_id' => '14'],
          ['id' => '14102','nombre' => 'Corral','region_id' => '14'],
          ['id' => '14103','nombre' => 'Lanco','region_id' => '14'],
          ['id' => '14104','nombre' => 'Los Lagos','region_id' => '14'],
          ['id' => '14105','nombre' => 'Máfil','region_id' => '14'],
          ['id' => '14106','nombre' => 'Mariquina','region_id' => '14'],
          ['id' => '14107','nombre' => 'Paillaco','region_id' => '14'],
          ['id' => '14108','nombre' => 'Panguipulli','region_id' => '14'],
          ['id' => '14201','nombre' => 'La Unión','region_id' => '14'],
          ['id' => '14202','nombre' => 'Futrono','region_id' => '14'],
          ['id' => '14203','nombre' => 'Lago Ranco','region_id' => '14'],
          ['id' => '14204','nombre' => 'Río Bueno','region_id' => '14'],
          ['id' => '15101','nombre' => 'Arica','region_id' => '15'],
          ['id' => '15102','nombre' => 'Camarones','region_id' => '15'],
          ['id' => '15201','nombre' => 'Putre','region_id' => '15'],
          ['id' => '15202','nombre' => 'General Lagos','region_id' => '15']
        ]);
    }
}
