<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\General\Pais;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Pais::insert([

            ['id' => '101','descripcion' => 'Angola','orden' => '0'],
            ['id' => '102','descripcion' => 'Argelia','orden' => '0'],
            ['id' => '103','descripcion' => 'Benin','orden' => '0'],
            ['id' => '104','descripcion' => 'Botswana','orden' => '0'],
            ['id' => '105','descripcion' => 'Burkina faso','orden' => '0'],
            ['id' => '106','descripcion' => 'Burundi','orden' => '0'],
            ['id' => '107','descripcion' => 'Cabo Verde','orden' => '0'],
            ['id' => '108','descripcion' => 'Camerun','orden' => '0'],
            ['id' => '109','descripcion' => 'Chad','orden' => '0'],
            ['id' => '110','descripcion' => 'Comores','orden' => '0'],
            ['id' => '111','descripcion' => 'Costa de Marfil','orden' => '0'],
            ['id' => '112','descripcion' => 'Djibouti','orden' => '0'],
            ['id' => '113','descripcion' => 'Egipto','orden' => '0'],
            ['id' => '114','descripcion' => 'Eritrea','orden' => '0'],
            ['id' => '115','descripcion' => 'Etiopia','orden' => '0'],
            ['id' => '116','descripcion' => 'Gabon','orden' => '0'],
            ['id' => '117','descripcion' => 'Gambia','orden' => '0'],
            ['id' => '118','descripcion' => 'Ghana','orden' => '0'],
            ['id' => '119','descripcion' => 'Guinea','orden' => '0'],
            ['id' => '120','descripcion' => 'Guinea - Bissau','orden' => '0'],
            ['id' => '121','descripcion' => 'Guinea ecuatorial','orden' => '0'],
            ['id' => '122','descripcion' => 'Guinea francesa','orden' => '0'],
            ['id' => '123','descripcion' => 'Kenya','orden' => '0'],
            ['id' => '124','descripcion' => 'Lesotho','orden' => '0'],
            ['id' => '125','descripcion' => 'Liberia','orden' => '0'],
            ['id' => '126','descripcion' => 'Libia','orden' => '0'],
            ['id' => '127','descripcion' => 'Madagascar','orden' => '0'],
            ['id' => '128','descripcion' => 'Malawi','orden' => '0'],
            ['id' => '129','descripcion' => 'Mali','orden' => '0'],
            ['id' => '130','descripcion' => 'Marruecos','orden' => '0'],
            ['id' => '131','descripcion' => 'Mauricio','orden' => '0'],
            ['id' => '132','descripcion' => 'Mauritania','orden' => '0'],
            ['id' => '133','descripcion' => 'Mayotte','orden' => '0'],
            ['id' => '134','descripcion' => 'Mozambique','orden' => '0'],
            ['id' => '135','descripcion' => 'Namibia','orden' => '0'],
            ['id' => '136','descripcion' => 'Niger','orden' => '0'],
            ['id' => '137','descripcion' => 'Nigeria','orden' => '0'],
            ['id' => '138','descripcion' => 'República Centroafricana','orden' => '0'],
            ['id' => '139','descripcion' => 'República del Congo','orden' => '0'],
            ['id' => '140','descripcion' => 'República Democrática del Congo','orden' => '0'],
            ['id' => '141','descripcion' => 'Reunion','orden' => '0'],
            ['id' => '142','descripcion' => 'Ruanda','orden' => '0'],
            ['id' => '143','descripcion' => 'Sahara Occidental','orden' => '0'],
            ['id' => '144','descripcion' => 'Santa Elena','orden' => '0'],
            ['id' => '145','descripcion' => 'Santo Tome y Principe','orden' => '0'],
            ['id' => '146','descripcion' => 'Senegal','orden' => '0'],
            ['id' => '147','descripcion' => 'Seychelles','orden' => '0'],
            ['id' => '148','descripcion' => 'Sierra Leona','orden' => '0'],
            ['id' => '149','descripcion' => 'Somalia','orden' => '0'],
            ['id' => '150','descripcion' => 'Sudafrica','orden' => '0'],
            ['id' => '151','descripcion' => 'Sudan','orden' => '0'],
            ['id' => '152','descripcion' => 'Swazilandia','orden' => '0'],
            ['id' => '153','descripcion' => 'Tanzania','orden' => '0'],
            ['id' => '154','descripcion' => 'Togo','orden' => '0'],
            ['id' => '155','descripcion' => 'Tunez','orden' => '0'],
            ['id' => '156','descripcion' => 'Uganda','orden' => '0'],
            ['id' => '157','descripcion' => 'Zaire','orden' => '0'],
            ['id' => '158','descripcion' => 'Zambia','orden' => '0'],
            ['id' => '159','descripcion' => 'Zimbabwe','orden' => '0'],
            ['id' => '201','descripcion' => 'Anguilla','orden' => '0'],
            ['id' => '202','descripcion' => 'Antigua y Barbuda','orden' => '0'],
            ['id' => '203','descripcion' => 'Antillas Holandesas','orden' => '0'],
            ['id' => '204','descripcion' => 'Argentina','orden' => '0'],
            ['id' => '205','descripcion' => 'Aruba','orden' => '0'],
            ['id' => '206','descripcion' => 'Bahamas','orden' => '0'],
            ['id' => '207','descripcion' => 'Barbados','orden' => '0'],
            ['id' => '208','descripcion' => 'Belice','orden' => '0'],
            ['id' => '209','descripcion' => 'Bermudas','orden' => '0'],
            ['id' => '210','descripcion' => 'Bolivia','orden' => '0'],
            ['id' => '211','descripcion' => 'Brasil','orden' => '0'],
            ['id' => '212','descripcion' => 'Canada','orden' => '0'],
            ['id' => '214','descripcion' => 'Colombia','orden' => '0'],
            ['id' => '215','descripcion' => 'Costa rica','orden' => '0'],
            ['id' => '216','descripcion' => 'Cuba','orden' => '0'],
            ['id' => '217','descripcion' => 'Dominica','orden' => '0'],
            ['id' => '218','descripcion' => 'Ecuador','orden' => '0'],
            ['id' => '219','descripcion' => 'El Salvador','orden' => '0'],
            ['id' => '220','descripcion' => 'Estados Unidos de America','orden' => '0'],
            ['id' => '221','descripcion' => 'Granada','orden' => '0'],
            ['id' => '222','descripcion' => 'Groenlandia','orden' => '0'],
            ['id' => '223','descripcion' => 'Guadalupe','orden' => '0'],
            ['id' => '224','descripcion' => 'Guatemala','orden' => '0'],
            ['id' => '225','descripcion' => 'Guyana','orden' => '0'],
            ['id' => '226','descripcion' => 'Guyana Francesa','orden' => '0'],
            ['id' => '227','descripcion' => 'Haiti','orden' => '0'],
            ['id' => '228','descripcion' => 'Honduras','orden' => '0'],
            ['id' => '229','descripcion' => 'Islas Caiman','orden' => '0'],
            ['id' => '230','descripcion' => 'Islas Georgia del Sur','orden' => '0'],
            ['id' => '231','descripcion' => 'Islas Malvinas','orden' => '0'],
            ['id' => '232','descripcion' => 'Islas Turcos y caicos','orden' => '0'],
            ['id' => '233','descripcion' => 'Islas Virgenes Americanas','orden' => '0'],
            ['id' => '234','descripcion' => 'Islas Virgenes Britanicas','orden' => '0'],
            ['id' => '235','descripcion' => 'Jamaica','orden' => '0'],
            ['id' => '236','descripcion' => 'Martinica','orden' => '0'],
            ['id' => '237','descripcion' => 'Mexico','orden' => '0'],
            ['id' => '238','descripcion' => 'Monserrat','orden' => '0'],
            ['id' => '239','descripcion' => 'Nicaragua','orden' => '0'],
            ['id' => '240','descripcion' => 'Panama','orden' => '0'],
            ['id' => '241','descripcion' => 'Paraguay','orden' => '0'],
            ['id' => '242','descripcion' => 'Peru','orden' => '0'],
            ['id' => '243','descripcion' => 'Puerto Rico','orden' => '0'],
            ['id' => '244','descripcion' => 'República Dominicana','orden' => '0'],
            ['id' => '245','descripcion' => 'San Cristobal y Nevis','orden' => '0'],
            ['id' => '246','descripcion' => 'San Pedro y Miquelon','orden' => '0'],
            ['id' => '247','descripcion' => 'San Vincente y las Granadinas','orden' => '0'],
            ['id' => '248','descripcion' => 'Santa Lucia','orden' => '0'],
            ['id' => '249','descripcion' => 'Surinam','orden' => '0'],
            ['id' => '250','descripcion' => 'Trinidad y Tobago','orden' => '0'],
            ['id' => '251','descripcion' => 'Uruguay','orden' => '0'],
            ['id' => '252','descripcion' => 'Venezuela','orden' => '0'],
            ['id' => '301','descripcion' => 'Afganistan','orden' => '0'],
            ['id' => '302','descripcion' => 'Arabia Saudita','orden' => '0'],
            ['id' => '303','descripcion' => 'Armenia','orden' => '0'],
            ['id' => '304','descripcion' => 'Azerbaiyan','orden' => '0'],
            ['id' => '305','descripcion' => 'Bahrein','orden' => '0'],
            ['id' => '306','descripcion' => 'Bangladesh','orden' => '0'],
            ['id' => '307','descripcion' => 'Bhutan','orden' => '0'],
            ['id' => '308','descripcion' => 'Birmania','orden' => '0'],
            ['id' => '309','descripcion' => 'Brunei','orden' => '0'],
            ['id' => '310','descripcion' => 'Camboya','orden' => '0'],
            ['id' => '311','descripcion' => 'China','orden' => '0'],
            ['id' => '312','descripcion' => 'Emiratos Arabes Unidos','orden' => '0'],
            ['id' => '313','descripcion' => 'Filipinas','orden' => '0'],
            ['id' => '314','descripcion' => 'Georgia','orden' => '0'],
            ['id' => '315','descripcion' => 'Hong Kong','orden' => '0'],
            ['id' => '316','descripcion' => 'India','orden' => '0'],
            ['id' => '317','descripcion' => 'Indonesia','orden' => '0'],
            ['id' => '318','descripcion' => 'Irak','orden' => '0'],
            ['id' => '319','descripcion' => 'Iran','orden' => '0'],
            ['id' => '320','descripcion' => 'Israel','orden' => '0'],
            ['id' => '321','descripcion' => 'Japon','orden' => '0'],
            ['id' => '322','descripcion' => 'Jordania','orden' => '0'],
            ['id' => '323','descripcion' => 'Kazajstan','orden' => '0'],
            ['id' => '324','descripcion' => 'Kirguizistan','orden' => '0'],
            ['id' => '325','descripcion' => 'Kuwait','orden' => '0'],
            ['id' => '326','descripcion' => 'Laos','orden' => '0'],
            ['id' => '327','descripcion' => 'Libano','orden' => '0'],
            ['id' => '328','descripcion' => 'Macau','orden' => '0'],
            ['id' => '329','descripcion' => 'Malasia','orden' => '0'],
            ['id' => '330','descripcion' => 'Maldivas','orden' => '0'],
            ['id' => '331','descripcion' => 'Mongolia','orden' => '0'],
            ['id' => '332','descripcion' => 'Nepal','orden' => '0'],
            ['id' => '333','descripcion' => 'Oman','orden' => '0'],
            ['id' => '334','descripcion' => 'Pakistan','orden' => '0'],
            ['id' => '335','descripcion' => 'Palestina','orden' => '0'],
            ['id' => '336','descripcion' => 'Qatar','orden' => '0'],
            ['id' => '337','descripcion' => 'República de Corea','orden' => '0'],
            ['id' => '338','descripcion' => 'República Democrática Popular de Corea','orden' => '0'],
            ['id' => '339','descripcion' => 'Rusia','orden' => '0'],
            ['id' => '340','descripcion' => 'Singapur','orden' => '0'],
            ['id' => '341','descripcion' => 'Siria','orden' => '0'],
            ['id' => '342','descripcion' => 'Sri lanka','orden' => '0'],
            ['id' => '343','descripcion' => 'Tailandia','orden' => '0'],
            ['id' => '344','descripcion' => 'Taiwan','orden' => '0'],
            ['id' => '345','descripcion' => 'Tayikistan','orden' => '0'],
            ['id' => '346','descripcion' => 'Turkmenistan','orden' => '0'],
            ['id' => '347','descripcion' => 'Turquia','orden' => '0'],
            ['id' => '348','descripcion' => 'Uzbekistan','orden' => '0'],
            ['id' => '349','descripcion' => 'Vietnam','orden' => '0'],
            ['id' => '350','descripcion' => 'Yemen','orden' => '0'],
            ['id' => '401','descripcion' => 'Albania','orden' => '0'],
            ['id' => '402','descripcion' => 'Alemania','orden' => '0'],
            ['id' => '403','descripcion' => 'Andorra','orden' => '0'],
            ['id' => '404','descripcion' => 'Austria','orden' => '0'],
            ['id' => '405','descripcion' => 'Belgica','orden' => '0'],
            ['id' => '406','descripcion' => 'Bielorrusia','orden' => '0'],
            ['id' => '407','descripcion' => 'Bosnia - Herzegovina','orden' => '0'],
            ['id' => '408','descripcion' => 'Bulgaria','orden' => '0'],
            ['id' => '409','descripcion' => 'Chipre','orden' => '0'],
            ['id' => '410','descripcion' => 'Croacia','orden' => '0'],
            ['id' => '411','descripcion' => 'Dinamarca','orden' => '0'],
            ['id' => '412','descripcion' => 'Eslovaquia','orden' => '0'],
            ['id' => '413','descripcion' => 'Eslovenia','orden' => '0'],
            ['id' => '414','descripcion' => 'España','orden' => '0'],
            ['id' => '415','descripcion' => 'Estonia','orden' => '0'],
            ['id' => '416','descripcion' => 'Finlandia','orden' => '0'],
            ['id' => '417','descripcion' => 'Francia','orden' => '0'],
            ['id' => '418','descripcion' => 'Gibraltar','orden' => '0'],
            ['id' => '419','descripcion' => 'Grecia','orden' => '0'],
            ['id' => '420','descripcion' => 'Holanda','orden' => '0'],
            ['id' => '421','descripcion' => 'Hungria','orden' => '0'],
            ['id' => '422','descripcion' => 'Irlanda','orden' => '0'],
            ['id' => '423','descripcion' => 'Islandia','orden' => '0'],
            ['id' => '424','descripcion' => 'Islas Feroe','orden' => '0'],
            ['id' => '425','descripcion' => 'Italia','orden' => '0'],
            ['id' => '426','descripcion' => 'Letonia','orden' => '0'],
            ['id' => '427','descripcion' => 'Liechtenstein','orden' => '0'],
            ['id' => '428','descripcion' => 'Lituania','orden' => '0'],
            ['id' => '429','descripcion' => 'Luxemburgo','orden' => '0'],
            ['id' => '430','descripcion' => 'Macedonia','orden' => '0'],
            ['id' => '431','descripcion' => 'Malta','orden' => '0'],
            ['id' => '432','descripcion' => 'Monaco','orden' => '0'],
            ['id' => '433','descripcion' => 'Noruega','orden' => '0'],
            ['id' => '434','descripcion' => 'Polonia','orden' => '0'],
            ['id' => '435','descripcion' => 'Portugal','orden' => '0'],
            ['id' => '436','descripcion' => 'Reino Unido','orden' => '0'],
            ['id' => '437','descripcion' => 'República Checa','orden' => '0'],
            ['id' => '438','descripcion' => 'República de Moldavia','orden' => '0'],
            ['id' => '439','descripcion' => 'Rumania','orden' => '0'],
            ['id' => '440','descripcion' => 'San Marino','orden' => '0'],
            ['id' => '441','descripcion' => 'Suecia','orden' => '0'],
            ['id' => '442','descripcion' => 'Suiza','orden' => '0'],
            ['id' => '443','descripcion' => 'Ucrania','orden' => '0'],
            ['id' => '444','descripcion' => 'Vaticano','orden' => '0'],
            ['id' => '445','descripcion' => 'Yugoslavia','orden' => '0'],
            ['id' => '501','descripcion' => 'Ashmore y Cartier','orden' => '0'],
            ['id' => '502','descripcion' => 'Australia','orden' => '0'],
            ['id' => '503','descripcion' => 'Christmas','orden' => '0'],
            ['id' => '504','descripcion' => 'Estados Federados de Micronesia','orden' => '0'],
            ['id' => '505','descripcion' => 'Fiji','orden' => '0'],
            ['id' => '506','descripcion' => 'Guam','orden' => '0'],
            ['id' => '507','descripcion' => 'Isla Kingman Reef','orden' => '0'],
            ['id' => '508','descripcion' => 'Isla Lord Howe','orden' => '0'],
            ['id' => '509','descripcion' => 'Isla Norfolk','orden' => '0'],
            ['id' => '510','descripcion' => 'Isla Palmyra','orden' => '0'],
            ['id' => '511','descripcion' => 'Isla Wake','orden' => '0'],
            ['id' => '512','descripcion' => 'Islas Cocos','orden' => '0'],
            ['id' => '513','descripcion' => 'Islas Cook','orden' => '0'],
            ['id' => '514','descripcion' => 'Islas Jarvis','orden' => '0'],
            ['id' => '515','descripcion' => 'Islas Johnston','orden' => '0'],
            ['id' => '516','descripcion' => 'Islas Mariana del norte','orden' => '0'],
            ['id' => '517','descripcion' => 'Islas Marshall','orden' => '0'],
            ['id' => '518','descripcion' => 'Islas Midway','orden' => '0'],
            ['id' => '519','descripcion' => 'Islas Salomon','orden' => '0'],
            ['id' => '520','descripcion' => 'Islas Wallis y futuna','orden' => '0'],
            ['id' => '521','descripcion' => 'Kiribati','orden' => '0'],
            ['id' => '522','descripcion' => 'Macquarie','orden' => '0'],
            ['id' => '523','descripcion' => 'Nauru','orden' => '0'],
            ['id' => '524','descripcion' => 'Niue','orden' => '0'],
            ['id' => '525','descripcion' => 'Nueva Caledonia','orden' => '0'],
            ['id' => '526','descripcion' => 'Nueva Zelanda','orden' => '0'],
            ['id' => '527','descripcion' => 'Palau','orden' => '0'],
            ['id' => '528','descripcion' => 'Papua - Nueva Guinea','orden' => '0'],
            ['id' => '529','descripcion' => 'Pitcairn','orden' => '0'],
            ['id' => '530','descripcion' => 'Polinesia Francesa','orden' => '0'],
            ['id' => '531','descripcion' => 'Samoa Occidental','orden' => '0'],
            ['id' => '532','descripcion' => 'Samoa Oriental','orden' => '0'],
            ['id' => '533','descripcion' => 'Tokelau','orden' => '0'],
            ['id' => '534','descripcion' => 'Tonga','orden' => '0'],
            ['id' => '535','descripcion' => 'Tuvalu','orden' => '0'],
            ['id' => '536','descripcion' => 'Vanuatu','orden' => '0'],
            ['id' => '537','descripcion' => 'Chile','orden' => '-1']

        ]);
    }
}
